management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include:
          - "health"
eureka:
  instance:
    hostname: localhost
    ip-address: "*"
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka